apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yq582kkwn-python
  janus-idp.io/tekton: yq582kkwn-python
  backstage.io/kubernetes-id: yq582kkwn-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yq582kkwn-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
